spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/allInBox?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    password: 123456
    username: root
